exclude: migrations/.*\.py|Procfile|[aw]sgi\.py|node_modules|.git|\.polar|inputs/.*
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude: .+\.min\.(css|js)
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: detect-private-key
  - id: mixed-line-ending
    args: [--fix, lf]
- repo: https://github.com/asottile/pyupgrade
  rev: v3.17.0
  hooks:
  - id: pyupgrade
    args: [--py310-plus]
- repo: https://github.com/asottile/yesqa
  rev: v1.5.0
  hooks:
  - id: yesqa
- repo: https://github.com/myint/docformatter
  rev: v1.7.5
  hooks:
  - id: docformatter
    args: [--in-place]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.5
  hooks:
  - id: ruff
    args: [--fix]
  - id: ruff-format
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]
- repo: https://github.com/mrtazz/checkmake
  rev: 0.2.2
  hooks:
  - id: checkmake
- repo: https://github.com/tox-dev/pyproject-fmt
  rev: 2.2.3
  hooks:
  - id: pyproject-fmt
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v4.0.0-alpha.8
  hooks:
  - id: prettier
    types_or: [css, javascript]
    exclude: .min.
- repo: local
  hooks:
  - id: cog
    name: Update css files
    entry: cog -rc
    language: system
    types: [css]
    exclude: .min.
    stages: [pre-commit]
