# Generated by Django 5.1.1 on 2024-09-11 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='name',
        ),
    ]
