# Generated by Django 5.1.1 on 2024-09-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_remove_dog_name'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='images',
            field=models.ManyToManyField(blank=True, to='wagtailimages.image'),
        ),
    ]
