# Generated by Django 5.1.1 on 2024-09-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_remove_dog_images_dogimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='dob',
        ),
        migrations.AddField(
            model_name='dog',
            name='body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
