# Generated by Django 5.1.1 on 2024-09-18 19:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0005_remove_dog_dob_dog_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='body',
            field=wagtail.fields.RichTextField(),
        ),
    ]
