# Generated by Django 5.1.1 on 2024-09-16 19:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_from_address_homepage_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='thank_you_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
