# Generated by Django 5.1.1 on 2024-09-16 19:48

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_thank_you_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='submit_text',
            field=models.CharField(default='Submit', help_text="Text that will appear on the form's submit button", max_length=255, verbose_name='Submit button text'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('Section', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('home.blocks.TitleBlock', (), {}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('dogs.blocks.DogListBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[]], {}), 5: ('wagtail.blocks.StreamBlock', [[('SiteTitle', 1), ('Paragraph', 2), ('Dogs', 3), ('Form', 4)]], {}), 6: ('wagtail.blocks.StructBlock', [[('navigation_title', 0), ('body', 5)]], {})}),
        ),
    ]
